"""new fields in user model

Revision ID: 202edc6c7cf9
Revises: 1a9e1f90cd64
Create Date: 2018-09-17 21:00:11.955291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202edc6c7cf9'
down_revision = '1a9e1f90cd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mdlist', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mdlist')
    # ### end Alembic commands ###
