"""logged in uer

Revision ID: a2504d5a2bc6
Revises: 05d07c64fec1
Create Date: 2018-09-19 20:35:20.711172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2504d5a2bc6'
down_revision = '05d07c64fec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('logged_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'logged_in')
    # ### end Alembic commands ###
